name: crossplatform

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-cross:
    # The type of runner that the job will run on
    runs-on: macos-latest

    strategy:
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            archname: x86_64
          - arch: arm64
            archname: arm64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: ${{ matrix.arch }}
      - run: |
          arch -arch ${{ matrix.archname }} python -m venv .venv
          source .venv/bin/activate
          python -c '
          import platform, pprint
          print("uname", *platform.uname())
          print("architecture", *platform.architecture())
          print("processor", platform.processor())
          '
          echo "---"
          arch -arch ${{ matrix.archname }} -c '
          import platform, pprint
          print("uname", *platform.uname())
          print("architecture", *platform.architecture())
          print("processor", platform.processor())
          '
