name: crossplatform

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-cross:
    # The type of runner that the job will run on
    runs-on: macos-latest

    strategy:
      matrix:
        archname: [x86_64, arm64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: arch(1)
        run: |
          echo "#!/usr/bin/env python
          
          import platform
          print(platform.processor())
          " > script
          cat script
          echo "==="
          chmod +x script
          ./script
          echo "==="
          arch -arch ${{ matrix.archname }} ./script
